### ISSUE TITLE
Refactor system tests to use new framework

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#34]
### Description
With the development of automatic provision and deployment libraries in Jenkins for system and E2E test automation, it is required to refactor system tests. These should be adapted to allow remote execution in the remote environment provisioned by Jenkins.

### General refactor requirements

- Allow custom remove execution using the `--inventory-path` pytest argument 
- Move from docker provisioning custom cases or test module configuration to fixture-based (changing manager/agent configuration or local_internal_option )
- Combine environment if possible
- If applicable, extend support to non-Linux operating systems
- If applicable, create custom roles for testing
- Create environment deployment/provisioning file for Jenkins automation

### Environment list
- [x] wazuh/wazuh-qa#3320
- [x] wazuh/wazuh-qa#3321
- [x] wazuh/wazuh-qa#3153
- [x] wazuh/wazuh-qa#3152
- [x] wazuh/wazuh-qa#3322
- [x] wazuh/wazuh-qa#3323
- [x] wazuh/wazuh-qa#3324
- [x] wazuh/wazuh-qa#2993
