### ISSUE TITLE
Improve QA Framework to allow Sytem test automation

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#35]
### Description

With the development of pipelines capable of deploying E2E Wazuh environments, it becomes necessary to incorporate system tests into CI processes.
Currently, system tests use docker environments to deploy managers and agents. This approach makes it impossible to automate pipelines in a scalable way, furthermore, it performs test configuration within the provisioning process, which unequivocally links environments with specific tests making it impossible to reuse those environments.

Given this need, we need to create a framework capable of managing the operations of the current system tests in a fast and intuitive way. In addition, it should also support Windows/macOS/Solaris systems.

```mermaid
flowchart TB
    subgraph Jenkins
    A[WazuhQAEnvironment] --> |Deployment&Provision| B[EnvironmentInventory]
    end
    subgraph pytest
    C[System Tests] -->  B[EnvironmentInventory] --> D[WazuhHandler] --> Report
    end
```

### Design

We propose the development of a new class `WazuhHandler`. This class will inherit from the already defined HostManager.
HostManager class will be responsible only for low-level operations (files and process handling). WazuhHandler instead, will handle the environment at a high level (Wazuh configuration, API requests, Agent removal, etc). 

```mermaid
classDiagram
HostManager <|-- WazuhHandler
    class HostManager{
        +Map move_file
        +Map create_file
        +Map modify_file_content
        +Map truncate_file
        +Map remove_file
        +Map run_command
        +Map run_shell
        +Map find_file
        +Map get_hot_ip
    }
    class WazuhHandler{
        +Map configure_environment
        +Map set_manager_agent_configuration
        +Map get_configuration_path
        +Map get_log_path
        +Map create_local_internal_configuration
        +Map log_search
        +Map is_windows
        +Map is_linux
        +Map get_host_variables
        +Map get_managers
        +Map get_agents
        +Map get_hosts
        +Map restart_agents
        +Map get_agents_id
        +Map restart_managers
        +Map make_api_call
        +Map clean_agents
    }
```

Summarizing, this new class should be able to execute the following basic operations of an environment:
- Agent/Manager Configuration
- Creation/Modification/Deletion of files and directories
- Registration/Deletion of agents
- Execution of commands in agents
- Executing operations in the API
- Monitoring of the different Wazuh's logs

It is important to highlight that all the class methods should:
- Be able to be executed in parallel. Otherwise, the tests would be too slow in large environments.
- Report through loggers the status in case of indicating sufficient debug level.
- Correctly manage errors in Testinfra operations.

### To Do

- [x] wazuh/qa-system-framework#36
- [x] https://github.com/wazuh/qa-system-framework/issues/27
- [ ] Wazuh Handler:
  - [x] wazuh/wazuh-qa#3595
  - [x] wazuh/qa-system-framework#28
  - [x] wazuh/qa-system-framework#29
  - [x] wazuh/qa-system-framework#30
  - [ ] wazuh/qa-system-framework#31
  - [x] https://github.com/wazuh/qa-system-framework/issues/65
  - [x] https://github.com/wazuh/qa-system-framework/issues/66
- [ ] wazuh/qa-system-framework#32
- [ ] wazuh/qa-system-framework#33
- [ ] https://github.com/wazuh/qa-system-framework/issues/34

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
